auto: false
markdown: rdiscount
pygments: true
permalink: /:year/:month/:title.html
exclude:
- Gemfile
- Gemfile.lock
- Rakefile
- README.markdown
- config.ru
- config.rb
- test.html
- sass
- images/src

